package protocol

const (
	VERSION uint8 = 0x30
)

// RequestId
const (
	SMGP_LOGIN = 0x00000001 + iota
	SMGP_SUBMIT
	SMGP_DELIVER
	SMGP_ACTIVE_TEST
	SMGP_FORWARD
	SMGP_EXIT
	SMGP_QUERY
	SMGP_QUERY_TE_ROUTE
	SMGP_QUERY_SP_ROUTE
	SMGP_PAYMENT_REQUEST
	SMGP_PAYMENT_AFFIRM
	SMGP_QUERY_USERSTATE
	SMGP_GET_ALL_TE_ROUTE
	SMGP_GET_ALL_SP_ROUTE
	SMGP_UPDATE_TE_ROUTE
	SMGP_UPDATE_SP_ROUTE
	SMGP_PUSH_UPDATE_TE_ROUTE
	SMGP_PUSH_UPDATE_SP_ROUTE
)

const (
	SMGP_LOGIN_RESP = 0x80000001 + iota
	SMGP_SUBMIT_RESP
	SMGP_DELIVER_RESP
	SMGP_ACTIVE_TEST_RESP
	SMGP_FORWARD_RESP
	SMGP_EXIT_RESP
	SMGP_QUERY_RESP
	SMGP_QUERY_TE_ROUTE_RESP
	SMGP_QUERY_SP_ROUTE_RESP
	SMGP_PAYMENT_REQUEST_RESP
	SMGP_PAYMENT_AFFIRM_RESP
	SMGP_QUERY_USERSTATE_RESP
	SMGP_GET_ALL_TE_ROUTE_RESP
	SMGP_GET_ALL_SP_ROUTE_RESP
	SMGP_UPDATE_TE_ROUTE_RESP
	SMGP_UPDATE_SP_ROUTE_RESP
	SMGP_PUSH_UPDATE_TE_ROUTE_RESP
	SMGP_PUSH_UPDATE_SP_ROUTE_RESP
)

// 客户端用来登录服务器端的登录模式
const (
	SEND_MODE = iota
	RECEIVE_MODE
	TRANSMIT_MODE
)

// MsgType
const (
	MO = 0 // MO消息（终端发给SP）
	MT = 6 // MT消息（SP发给终端，包括WEB上发送的点对点短消息）
)

// MsgFormat
// 短消息内容体的编码格式
// 对于文字短消息，要求MsgFormat＝15, 对于回执消息，要求MsgFormat＝0
const (
	ASCII   = 0  // ASCII编码
	BINARY  = 4  // 二进制短消息
	UCS2    = 8  // UCS2编码
	GB18030 = 15 // GB18030编码
)

const (
	NOT_REPORT = 0 // 不是状态报告
	IS_REPORT  = 1 // 是状态报告
)

// 是否要求返回状态报告
const (
	NO_NEED_REPORT = 0
	NEED_REPORT    = 1
)

// 短消息发送优先级
const (
	LOW_PRIORITY = iota
	NORMAL_PRIORITY
	HIGHER_PRIORITY
	HIGHEST_PRIORITY
)
